// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3HGo105CKHPsbLR2mRpvfwkGXN6YHqws',
    appId: '1:730625492472:web:bd8d8248eddc7a8e13820d',
    messagingSenderId: '730625492472',
    projectId: 'transikids-4fa03',
    authDomain: 'transikids-4fa03.firebaseapp.com',
    storageBucket: 'transikids-4fa03.firebasestorage.app',
    measurementId: 'G-WVV7KZT231',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60W8SQ5SXTe_z17VwRs7xGbZtCr98jVE',
    appId: '1:730625492472:android:74d406c9566ea87613820d',
    messagingSenderId: '730625492472',
    projectId: 'transikids-4fa03',
    storageBucket: 'transikids-4fa03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7LLjarWAzwWI-n53AyW5ue5K2oi3xDs',
    appId: '1:730625492472:ios:f380986ced80604613820d',
    messagingSenderId: '730625492472',
    projectId: 'transikids-4fa03',
    storageBucket: 'transikids-4fa03.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7LLjarWAzwWI-n53AyW5ue5K2oi3xDs',
    appId: '1:730625492472:ios:f380986ced80604613820d',
    messagingSenderId: '730625492472',
    projectId: 'transikids-4fa03',
    storageBucket: 'transikids-4fa03.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HGo105CKHPsbLR2mRpvfwkGXN6YHqws',
    appId: '1:730625492472:web:438022e64ad7032c13820d',
    messagingSenderId: '730625492472',
    projectId: 'transikids-4fa03',
    authDomain: 'transikids-4fa03.firebaseapp.com',
    storageBucket: 'transikids-4fa03.firebasestorage.app',
    measurementId: 'G-T7BG4DNNMZ',
  );
}
